feat: add resource limits and requests to ocean controller
spotinst/terraform-spotinst-ocean-eks pull request #27
Opened 2022-06-21 00:02 UTC by arifalkner

2022-06-21 00:34 UTC, mabelova approved these changes

2022-06-23 10:18 UTC, liranp requested changes

2022-06-23 10:18 UTC, liranp commented on ocean.tf
> +  resource_limits     = var.controller_resource_limits
```suggestion
  resources_limits     = var.controller_resources_limits
```

2022-06-23 10:18 UTC, liranp commented on ocean.tf
> +  resource_limits     = var.controller_resource_limits
[See](https://github.com/spotinst/terraform-spotinst-ocean-controller/blob/v0.38.0/variables.tf#L70-L78).

2022-06-23 10:18 UTC, liranp commented on ocean.tf
> +  resource_requests   = var.controller_resource_requests
```suggestion
  resources_requests   = var.controller_resources_requests
```

2022-06-23 10:18 UTC, liranp commented on ocean.tf
> +  resource_requests   = var.controller_resource_requests
[See](https://github.com/spotinst/terraform-spotinst-ocean-controller/blob/v0.38.0/variables.tf#L80-L88).

2022-06-25 21:58 UTC, liranp requested changes

2022-06-25 21:58 UTC, liranp commented on ocean.tf
> +  resources_limits    = var.controller_resource_limits
```suggestion
  resources_limits    = var.controller_resources_limits
```

2022-06-25 21:58 UTC, liranp commented on ocean.tf
> +  resources_requests  = var.controller_resource_requests
```suggestion
  resources_requests  = var.controller_resources_requests
```

2022-06-28 08:38 UTC, liranp approved these changes

2022-06-28 08:38 UTC, merged